# Generated by Django 4.2.5 on 2023-09-20 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SmartUrja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smarturja',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
